// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
	LINE_WEBHOOK_SECRETKEY: string;
	LINE_API_TOKEN: string;
	DISCORD_WEBHOOK_LINK: string;
}
